name: package-helm-chart

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Helm charts matrix
        id: set-matrix
        run: |
          CHARTS_PATHS=$(find ./charts -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | jq -R -s -c 'split("\n")[:-1]')
          echo "Matrix: $CHARTS_PATHS"
          echo "matrix=$CHARTS_PATHS" >> $GITHUB_OUTPUT

  build:
    permissions:
      contents: read
      packages: write

    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Helm chart version
        run: |
          VERSION=$(yq -r .version ./charts/${{ matrix.chart }}/Chart.yaml)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: helm lint
        run: |
          helm lint ./charts/${{ matrix.chart }}/

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and push helm chart
        run: |
          helm package ./charts/${{ matrix.chart }} --version ${{ env.VERSION }}
          helm push ./${{ matrix.chart }}-${{ env.VERSION }}.tgz oci://ghcr.io/${{ github.actor }}/helm-charts