name: package-helm-chart

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
  
  workflow_dispatch:

jobs:
  prepare-matrix:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Prepare Helm charts matrix
        id: set-matrix
        run: |
          # Find chart directories inside the 'charts' folder and create a matrix
          CHARTS_PATHS=$(find ./charts -mindepth 1 -maxdepth 1 -type d -exec basename {} \;)
          MATRIX=$(echo "${CHARTS_PATHS}" | tr ' ' '\n' | jq -R . | jq -s .)
          echo "Matrix: $MATRIX"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set Helm chart version
        run: |
          VERSION=$(yq -r .version ./charts/${{ matrix.chart }}/Chart.yaml)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Package and push helm chart
        run: |
          helm package ./charts/${{ matrix.chart }} --version ${{ env.VERSION }}
          helm push ./${{ matrix.chart }}-${{ env.VERSION }}.tgz oci://${{ env.REPOSITORY }}/charts